// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// separate_cpp
DataFrame separate_cpp(const std::vector<int>& Year, const std::vector<int>& Mon, const std::vector<int>& Day, const std::vector<double>& Qin, const std::vector<double>& Tin, const std::vector<double>& Pin, List params);
RcppExport SEXP _grwat_separate_cpp(SEXP YearSEXP, SEXP MonSEXP, SEXP DaySEXP, SEXP QinSEXP, SEXP TinSEXP, SEXP PinSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Year(YearSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Mon(MonSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type Day(DaySEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type Qin(QinSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type Tin(TinSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type Pin(PinSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(separate_cpp(Year, Mon, Day, Qin, Tin, Pin, params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grwat_separate_cpp", (DL_FUNC) &_grwat_separate_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_grwat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
