#' Plot hydrograph separation
#'
#' @param df data.frame with hydrograph separation
#' @param years a vector of years to be plotted
#' @param layout layout matrix
#' @param pagebreak logical. Whether to break page between plots (needed for reporting). Defaults to FALSE
#' @param locale string locale. Currently only English locale is supported. Defaults to 'EN'. 
#'
#' @return ggplot2 objects
#' @export
plot_separation <- function(df, years = NULL, layout = as.matrix(1), pagebreak = FALSE, locale='EN'){
  
  if (locale == 'RU') {
    Sys.setenv(LANGUAGE="ru")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "ru_RU.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "Russian"))
    
  } else {
    Sys.setenv(LANGUAGE="en")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "en_US.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "English"))
  }
  
  df = df %>% dplyr::mutate(Year = lubridate::year(Date))
  
  if(!is.null(years)){
    df = df %>% dplyr::filter(Year %in% years)
  }
  
  yrs = df %>% dplyr::group_by(Year) %>% 
    dplyr::summarise(nydate = Date[which(Qpol>0)[1]],
                     datepolend = max(Date[which(Qpol>0)])) %>% 
    dplyr::filter(!is.na(nydate))
  
  n = nrow(yrs)
  
  max.runoff = max(df$Qin)
  
  labs = get_plot_labels(locale)
  plotlist = list()
  j = 1
  
  for (i in 1:n) {
    begin.date = yrs$nydate[i]
    end.date = lubridate::ceiling_date(begin.date, "year") - lubridate::days(1) # Initialize by the end of the year
    
    clipped.remark = labs$clipped.remark
    year = yrs$Year[i]
    
    datestart = begin.date
    lubridate::year(datestart) = lubridate::year(begin.date)
    
    datepolend = yrs$datepolend[i]
    lubridate::year(datepolend) = lubridate::year(begin.date)
    
    if (i != n){
      nextyear <- yrs$Year[i+1]
      if ((nextyear - year) == 1) {
        end.date = yrs$nydate[i+1] - lubridate::days(1) # Change to the end date of water-resources year
        clipped.remark = ""
      }
    }
    
    graphdata = df %>%  
      dplyr::filter(dplyr::between(Date, begin.date, end.date)) %>% 
      tidyr::gather(key="Runtype", value="Runoff", 
             Qthaw, Qpav, Qpol, Qgr,
             factor_key=TRUE)
    
    graphdata$Runtype = factor(graphdata$Runtype,
                               levels = c("Qthaw", "Qpav", "Qpol", "Qgr"),
                               labels = c("Thaw", "Rain", "Seasonal", "Ground"))
    
    g = ggplot(graphdata, aes(x=Date, y=Runoff, fill=Runtype)) + 
      annotate("rect", 
               xmin = datestart, xmax = datepolend,
               ymax = max.runoff, ymin = 0,
               fill = 'black',
               alpha = 0.1) +
      geom_area() + 
      geom_vline(xintercept = datestart, color = "black", size=0.3) +
      geom_vline(xintercept = datepolend, color = "black", size=0.3) +
      annotate("text", label = format(datestart, format="%d-%m"),
               x = datestart + 20, y = 0.95 * max.runoff,
               size = 3, colour = "black") +
      annotate("text", label = format(datepolend, format="%d-%m"), 
               x = datepolend + 20, y = 0.95 * max.runoff, 
               size = 3, colour = "black") +
      coord_cartesian(ylim=c(0, max.runoff)) +
      scale_fill_manual(values=c("blue", "darkgreen", "steelblue", "violetred"), 
                        name = "Discharge:") +
      scale_x_date(date_breaks = "1 month", date_labels = "%b") +
      labs(title = year,
           subtitle = paste(begin.date, "-", end.date, clipped.remark),
           x = labs$date, y = substitute(d ~ ', ' ~ m, list(d = labs$discharge, m = labs$m3s))) +
      theme(plot.title = element_text(lineheight=.8, face="bold"),
            legend.position="bottom")
    
    plotlist[[j]] = g
    j = j+1
    if (j == length(layout)+1) {
      multiplot(plotlist = plotlist, layout = layout)
      if (pagebreak) cat("\n\n\\pagebreak\n")
      plotlist = list()
      j = 1
    }
  }
  
  if (j > 1) {
    multiplot(plotlist = plotlist, layout = layout)
  }
}

#' Plot interannual parameters
#'
#' @param df  data.frame produced by separation function (read by `read_separation()`)
#' @param ... quoted sequence of variable names
#' @param tests tests list for the same variables (generated by `test_variables()` function)
#' @param smooth logical. If true then local smoothing regression is plotted. Defaults to TRUE.
#' @param layout layout matrix
#' @param pagebreak logical. Whether to break page between plots (needed for reporting). Defaults to FALSE
#' @param locale string locale. Currently only English locale is supported. Defaults to 'EN'. 
#'
#' @return
#' @export
#'
#' @examples
plot_variables <- function(df, ..., tests = NULL, smooth = TRUE, layout = as.matrix(1), pagebreak = FALSE, locale='EN'){
  
  if (locale == 'RU') {
    Sys.setenv(LANGUAGE="ru")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "ru_RU.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "Russian"))
    
  } else {
    Sys.setenv(LANGUAGE="en")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "en_US.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "English"))
  }
  
  fields = rlang::exprs(...) %>% as.character()
  
  if(length(fields) == 0)
    fields = params_out %>% 
      dplyr::filter(Order != 0) %>% 
      dplyr::arrange(Order) %>% 
      dplyr::pull(Name)
  
  prms = params_out %>% 
            dplyr::filter(Name %in% fields) %>% 
            dplyr::slice(match(fields, Name))
  
  nn = nrow(prms)
  
  df = df %>% 
    dplyr::mutate_if(params_out$Winter == 1, replace_year)
  
  minyear = min(df$Year1)
  maxyear = max(df$Year1)
  breaks = scales::fullseq(c(minyear, maxyear), 10)
  minbreaks = scales::fullseq(c(minyear, maxyear), 5)
  
  labs = get_plot_labels(locale)
  
  units = switch(locale,
                 'RU' = prms$Units,
                 'EN' = prms$Unitsen)
  desc = switch(locale,
                'RU' = prms$Desc,
                'EN' = prms$Descen)
  
  plotlist = list()
  j = 1
  
  for (i in 1:nn) {
    
    # MAIN DATA FOR PLOTTING
    g = ggplot(df, aes_string(x = "Year1", y = prms$Name[i])) + 
      scale_x_continuous(breaks = breaks, minor_breaks = minbreaks) +
      labs(title = stringr::str_wrap(desc[i], width=labs$wraplength),
           x = labs$subtitle, 
           y = parse(text=units[i])) +
      theme(plot.title = element_text(size=12, lineheight=.8, face="bold"),
            panel.background = element_rect(fill = prms$Color[i],
                                            colour = prms$Color[i],
                                            size = 0.5, linetype = "solid"))
    
    if (smooth) {
      g = g + geom_smooth()
    }
    
    if (!is.null(tests)) {
      
      ltype="solid"
      ts_ltype="solid"
      
      if (tests$ptt[[i]]$p.value > 0.05) ltype = 'dashed'
      if (tests$tst[[i]]$p.value > 0.05) ts_ltype = 'dashed' 
      
      g = g +       
        geom_abline(intercept = coef(tests$ts_fit[[i]])[1], slope = coef(tests$ts_fit[[i]])[2], 
                                color = 'red', size=1, linetype = ts_ltype) +
        geom_vline(xintercept = tests$change_year[i], color = "red", 
                   size=0.5, linetype = ltype) +
        annotate("text", label = tests$change_year[i], 
                 x = tests$change_year[i] + 4, y = tests$maxval[[i]], 
                 size = 4, colour = "red") +
        labs(title = stringr::str_wrap(desc[i], width=labs$wraplength),
             subtitle = paste0(labs$pettitt.u, ' = ',  round(tests$ptt[[i]]$statistic, 3), ', ',
                               labs$label.p, ' = ', round(tests$ptt[[i]]$p.value, 5), '\n',
                               labs$kendall.z, ' = ', round(tests$mkt[[i]]$statistic, 3), ', ',
                               labs$label.p, ' = ', round(tests$mkt[[i]]$p.value, 5), '. ',
                               labs$theil.i, ' = ', round(coef(tests$ts_fit[[i]])[2], 5)))
    }
    
    date_labels = "%d-%b"

    # PLOT TYPE
    if (prms$Chart[i] == 'line') {
      g = g + geom_line() + geom_area(alpha = 0.3)
    } else if (prms$Chart[i] == 'point') {
      g = g + geom_point(size = 1.5) + geom_line(size = 0.2)
      date_labels = "%b"
    } else if (prms$Chart[i] == 'plate') {
      g = g + geom_point(shape = 15, size = 1.5) + geom_step(size = 0.2)
      date_labels = "%b"
    } else if (prms$Chart[i] == 'step') {
      g = g + geom_step() + geom_rect(aes_string(xmin = "Year1", 
                                                 xmax = "Year2", 
                                                 ymax = prms$Name[i], 
                                                 ymin = 0), 
                                      alpha = 0.4) +
        scale_y_continuous(limits = c(0, NA))
      date_labels = "%m"
    }
    
    # SPECIAL AXES FOR DATES
    if(prms$Units[i] %in% c('Date', 'Month')){
      if(prms$Winter[i] != 1) {
        g = g +
          scale_y_date(date_labels = date_labels, 
                       date_breaks = "2 month", 
                       limits = c(lubridate::ymd(20000101), lubridate::ymd(20001231))) +
          expand_limits(y = c(lubridate::ymd(20000101), lubridate::ymd(20001231)))
      } else {
        g = g +
          scale_y_date(date_labels = date_labels, 
                       date_breaks = "2 month", 
                       limits = c(lubridate::ymd(20000701), lubridate::ymd(20010630))) +
          expand_limits(y = c(lubridate::ymd(20000701), lubridate::ymd(20010630)))
      }
    }
    
    plotlist[[j]] = g
    j = j+1
    if (j == length(layout)+1) {
      multiplot(plotlist = plotlist, layout = layout)
      if (pagebreak) cat("\n\n\\pagebreak\n")
      plotlist = list()
      j = 1
    }
  }
  
  if (j > 1) {
    multiplot(plotlist = plotlist, layout = layout)
  }
}

#' Plot long-term changes of hydrograph variables for two periods
#'
#' @param df data.frame produced by description function (read by `read_variables()`)
#' @param ... quoted sequence of variable names
#' @param change_year change year value to separate two periods (overridden by tests if it is supplied)
#' @param tests tests list for the same variables (generated by `test_variables()` function)
#' @param layout layout matrix
#' @param pagebreak logical. Whether to break page between plots (needed for reporting). Defaults to FALSE
#' @param locale string locale. Currently only English locale is supported. Defaults to 'EN'. 
#'
#' @return ggplot2 objects
#' @export
plot_periods <- function(df, ..., change_year = NULL, tests = NULL, layout = as.matrix(1), pagebreak = FALSE, locale='EN'){
  
  if(is.null(change_year) & is.null(tests))
    stop('You must provide year or tests parameter')
  
  if (locale == 'RU') {
    Sys.setenv(LANGUAGE="ru")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "ru_RU.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "Russian"))
    
  } else {
    Sys.setenv(LANGUAGE="en")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "en_US.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "English"))
  }
  
  fields = rlang::exprs(...) %>% as.character()

  if(length(fields) == 0)
    fields = params_out %>% 
    dplyr::filter(Order != 0) %>% 
    dplyr::arrange(Order) %>% 
    dplyr::pull(Name)
  
  prms = params_out %>% 
    dplyr::filter(Name %in% fields) %>% 
    dplyr::slice(match(fields, Name))
  
  nn = nrow(prms)
  
  df = df %>% 
    dplyr::mutate_if(params_out$Winter == 1, replace_year)
  
  labs = get_plot_labels(locale)
  
  units = switch(locale,
                 'RU' = prms$Units,
                 'EN' = prms$Unitsen)
  desc = switch(locale,
                'RU' = prms$Desc,
                'EN' = prms$Descen)
  
  plotlist = list()
  j = 1
  
  for (i in 1:nn) {
    
    if(!is.null(tests)){
      change_year = tests$change_year[i]
    }
    
    d = df[prms$Name[i]] %>% 
      as.matrix() %>% 
      as.vector()
    
    is_date = FALSE
    if(prms$Unitsen[i] %in% c('Date', 'Month')){
      d = d %>% as.Date() %>% as.integer()
      is_date = TRUE
    }
    
    d1 = d[df$Year1 < change_year]
    d2 = d[df$Year1 >= change_year]
    
    n1 = length(d1)
    n2 = length(d2)
    
    periodtitle1 = paste0(labs$beforetitle, change_year)
    periodtitle2 = paste0(labs$aftertitle, change_year)
    
    df.plot = data.frame(Value = d, 
                    Period = c(rep(periodtitle1, n1), 
                               rep(periodtitle2, n2)))
    
    g = ggplot() + 
      geom_boxplot(data = df.plot, aes(x = Period, y = Value)) +
      coord_flip() +
      labs(title = stringr::str_wrap(desc[i], width=labs$wraplength),
           x = NULL, 
           y = parse(text=units[i])) +
      theme(plot.title = element_text(size=12, lineheight=.8, face="bold"),
            panel.background = element_rect(fill = prms$Color[i],
                                            colour = prms$Color[i],
                                            size = 0.5, linetype = "solid"))
    
    if (!is.null(tests)) {
      
      m1 = mean(d1, na.rm = TRUE)
      m2 = mean(d2, na.rm = TRUE)
      
      rsd1 = round(sd(d1, na.rm = TRUE)/m1, 3)
      rsd2 = round(sd(d2, na.rm = TRUE)/m2, 3)
      
      means <- df.plot %>% 
        dplyr::group_by(Period) %>% 
        dplyr::summarise(Value = mean(Value))
      
      mean1 = ifelse(is_date, 
                     m1 %>% as.integer() %>% as.Date(origin = '1970-01-01') %>% format("%d-%b"),
                     m1 %>% round(3)
      )
      
      mean2 = ifelse(is_date, 
                     m2 %>% as.integer() %>% as.Date(origin = '1970-01-01') %>% format("%d-%b"),
                     m2 %>% round(3)
      )
      
      m1 = ifelse(is_date,
                  m1 %>% as.integer(),
                  m1)
      
      m2 = ifelse(is_date,
                  m2 %>% as.integer(),
                  m2)
      
      pt.df = data.frame(Value = c(m1, m2), 
                         Period = c(periodtitle1, periodtitle2))
      
      g = g + 
        geom_point(data = pt.df, aes(x = Period, y = Value), colour="steelblue", shape=20, size=3) +
        labs(subtitle = paste0(labs$student.t, ' = ', round(tests$tt[[i]]$statistic, 3), ', ',
                               labs$label.p, ' = ', round(tests$tt[[i]]$p.value, 5), ', ',
                               'm1 = ', mean1, ', ', 
                               'm2 = ', mean2,
                               '\n',
                               labs$fisher.f, ' = ', round(tests$ft[[i]]$statistic, 3), ', ',
                               labs$label.p, ' = ', round(tests$ft[[i]]$p.value, 5), ', ',
                               'cv1 = ', rsd1, ', ',
                               'cv2 = ', rsd2))
    }
    
    if(is_date){
      g = g + scale_y_continuous(labels = function(x) {
        return(as.Date(x, origin = "1970-01-01") %>% format(format = '%d-%m'))
      })
    }
    
    plotlist[[j]] = g
    j = j+1
    if (j == length(layout)+1) {
      multiplot(plotlist = plotlist, layout = layout)
      if (pagebreak) cat("\n\n\\pagebreak\n")
      plotlist = list()
      j = 1
    }
  }
  
  if (j > 1) {
    multiplot(plotlist = plotlist, layout = layout)
  }
  
}

#' Plot histogram of minimum discharge month for two periods
#'
#' @param df data.frame produced by description function (read by `read_variables()`)
#' @param change_year change year value to separate two periods
#' @param locale string locale. Currently only English locale is supported. Defaults to 'EN'. 
#'
#' @return ggplot2 objects
#' @export
plot_minmonth <- function(df, change_year = NULL, pagebreak = FALSE, locale='EN'){
  
  if(is.null(change_year))
    stop('You must supply change_year parameter')
  
  if (locale == 'RU') {
    Sys.setenv(LANGUAGE="ru")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "ru_RU.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "Russian"))
    
  } else {
    Sys.setenv(LANGUAGE="en")
    switch(.Platform$OS.type,
           'unix' = Sys.setlocale("LC_ALL", "en_US.UTF-8"),
           'windows' = Sys.setlocale("LC_ALL", "English"))
  }
  
  labs = get_plot_labels(locale)
  
  periodtitle1 = paste0(labs$beforetitle, change_year)
  periodtitle2 = paste0(labs$aftertitle, change_year)
  
  chart.data = df %>% 
    dplyr::select(monmmsummer, nommwin, Year1) %>% 
    dplyr::filter(!is.na(monmmsummer) & !is.na(nommwin)) %>% 
    dplyr::mutate(summermonth = lubridate::month(monmmsummer),
                  wintermonth = lubridate::month(nommwin),
                  old = as.integer(Year1 >= change_year))
  
  chart.data$old = factor(chart.data$old, 
                          levels = c(0,1), 
                          labels = c(periodtitle1, periodtitle2))
  
  month.names = format(ISOdate(2017,1:12,1),"%m")
  winterlabels = month.names[c(7:12, 1:6)]
  
  chart.data$summermonth = ordered(chart.data$summermonth, 
                                   levels = 1:12, 
                                   labels = month.names)
  
  chart.data$wintermonth = ordered(chart.data$wintermonth, 
                                   levels = c(7:12, 1:6), 
                                   labels = winterlabels)
  
  df.summer = chart.data %>% 
    dplyr::group_by(old, summermonth) %>% 
    dplyr::tally() %>% 
    tidyr::complete(summermonth, tidyr::nesting(old), fill=list(n=0)) %>%  
    dplyr::mutate(perc = 100*n/sum(n))
  
  df.winter = chart.data %>% 
    dplyr::group_by(old, wintermonth) %>% 
    dplyr::tally() %>% 
    tidyr::complete(wintermonth, tidyr::nesting(old), fill=list(n=0)) %>%  
    dplyr::mutate(perc = 100*n/sum(n))
  
  df.summer.all = chart.data %>% 
    dplyr::group_by(summermonth) %>% 
    dplyr::tally() %>% 
    dplyr::mutate(perc = 100*n/sum(n))
  
  df.winter.all = chart.data %>% 
    dplyr::group_by(wintermonth) %>% 
    dplyr::tally() %>% 
    dplyr::mutate(perc = 100*n/sum(n))
  
  g.summer = ggplot() +
    geom_col(data = df.summer, 
             aes(x = summermonth, y = perc, fill = old), 
             position = "dodge") +
    geom_col(data = df.summer.all, 
             aes(x = summermonth, y = perc), 
             colour="black", 
             fill = NA, 
             size=1) +
    theme(plot.title = element_text(face="bold")) +
    scale_x_discrete(drop = FALSE) +
    scale_fill_manual(values=c("indianred1", "deepskyblue4"), 
                      name = labs$periodtitle) +
    labs(title = labs$bartitle.sum,
         x = labs$monthtitle, 
         y = "%")
  
  g.winter = ggplot() +
    geom_col(data = df.winter, 
             aes(x = wintermonth, y = perc, fill = old), 
             position = "dodge") +
    geom_col(data = df.winter.all, 
             aes(x = wintermonth, y = perc), 
             colour="black", 
             fill = NA, 
             size=1) +
    theme(plot.title = element_text(face="bold")) +
    scale_x_discrete(drop = FALSE) +
    scale_fill_manual(values=c("indianred1", "deepskyblue4"), 
                      name = labs$periodtitle) +
    labs(title = labs$bartitle.win,
         x = labs$monthtitle, 
         y = "%")
  multiplot(plotlist = list(g.summer, g.winter))
  if (pagebreak) cat("\n\n\\pagebreak\n")
}