# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_baseflow_cpp <- function(Qin, alpha, padding, passes, method) {
    .Call('_grwat_get_baseflow_cpp', PACKAGE = 'grwat', Qin, alpha, padding, passes, method)
}

separate_cpp <- function(Year, Mon, Day, Qin, Tin, Pin, params, niter) {
    .Call('_grwat_separate_cpp', PACKAGE = 'grwat', Year, Mon, Day, Qin, Tin, Pin, params, niter)
}

